### PR TITLE
V1.2.0

### PR DESCRIPTION
**Pull request by cat-haines**
- Fixed content-length bug (https://github.com/electricimp/Rocky/issues/7)
- Added documentation for CORS pre-flight checks (https://github.com/electricimp/Rocky/issues/5)
- Added Express JS style middleware (can be used for https://github.com/electricimp/Rocky/issues/3, https://github.com/electricimp/Rocky/issues/4)

### CODE REVIEW

**Comment by cat-haines** [comment]
@betzrhodes - let me know if you want to go through anything in detail :)

**Comment by betzrhodes** [comment]
Example code broken - 
  Rocky use(callback) 

app.on - missing a parameter, doesn't have a verb

**Comment by betzrhodes** [comment]
Example code broken - 
  Rocky.getContext(id)

app.on - missing a parameter, doesn't have a verb

device.on  - if statement broken, request times out
should be ....
    // then send the response using that context
    if (context.send) {
        context.send(200, { temp = data.temp });
    }
or 
    if (!context.sent) {
        context.send(200, { temp = data.temp });
    }

**Comment by betzrhodes** [comment]
Example code broken - 
Rocky.sendToAll(statuscode, response, [headers])

app.on - missing a parameter, doesn't have a verb

**Comment by betzrhodes** [comment]
Example code broken - 
Rocky.Route use(callback)

if ("username" in usernames) context.send(400, "Requested username already exists");
should be 
if (context.req.body.username in usernames) context.send(400, "Requested username already exists");

**Comment by betzrhodes** [comment]
Example code broken -
Rocky.context setHeader(headerName, data)

app.on - missing a parameter, doesn't have a verb

**Comment by betzrhodes** [comment]
typos - 
Rocky.context  - context.req
trailing markup code closing (```) at end of example

**Comment by betzrhodes** [comment]
Example code broken - 
Rocky.context  - context.userdata

app.on - missing a parameter, doesn't have a verb

**Comment by betzrhodes** [comment]
Rocky.context - context.matches 
example code is the same as context.path, context.match not used

**Comment by betzrhodes** [comment]
Rocky.context - context.isBrowser()
the code is lowercase - context.isbrowser, but the section title is camelcase

**Comment by betzrhodes** [comment]
Rocky.context - context.sent
this is used in some example code - may want to update if deprecated

Rocky.Route - onTimeout(callback) 
Rocky.getContext(id) ??

**Comment by cat-haines** [comment]
@betzrhodes - Updated README with changes. For minor typos, etc it's probably easier to just pull the branch, fix them, then push :)

**Comment by betzrhodes** [comment]
Added a couple small changes to the examples.  Take a look then this is ready to merge.

**Pull request merged**
