### PR TITLE
Fixed two timeout bugs. 

### PR DESCRIPTION
**Pull request by blindman2k**
One that caused the second execution of a route to fail, the other that ignored individual handler timeouts. Updated examples to use libraries.

### CODE REVIEW

**Comment by cat-haines** [comment]
I'm going to wait until you submit your other PR before updating in the Electric Imp library management system.

**Comment by blindman2k** [comment]
Thanks. Will submit now. You may not like it ... but I do :)

_Aron Steg_
_BCDE Investments, *_SMS Diagnostics, SMS Broker, Zaq, Explainers*
Mob: +61 4 3333 4444 or +1 415 728 6707 | Fax: +61 3 8677 7613

**Comment by blindman2k** [comment]
Weird ... Github took the other changes that I didn't put into the pull
request. Nothing more for me to do.

_Aron Steg_
_BCDE Investments, *_SMS Diagnostics, SMS Broker, Zaq, Explainers*
Mob: +61 4 3333 4444 or +1 415 728 6707 | Fax: +61 3 8677 7613

**Comment by cat-haines** [comment]
For some reason I missed that you added the broadcast function, not just modify it..

Broadcast is possibly a bad name - respondToAll might be better?

Also, what's the story / context for the broadcast function?

**Comment by blindman2k** [comment]
I am using it to create a collection of connected sessions and then respond
to all of them at once.
We already had the static _contexts array so I thought it would be good to
use it.
sendToAll() might be better :)

_Aron Steg_
_BCDE Investments, *_SMS Diagnostics, SMS Broker, Zaq, Explainers*
Mob: +61 4 3333 4444 or +1 415 728 6707 | Fax: +61 3 8677 7613

**Pull request merged**
